### ISSUE TITLE
Refresh automatically

### ISSUE THREAD

**Issue by raymondEhlers** [raymondEhlers/OVERWATCH#10]
Something like this should work fine: https://stackoverflow.com/a/8711918

**Comment by raymondEhlers** [comment]
I know this was on our list for a long time, but I'm not so convinced anymore that this is necessary. I don't think we really do monitoring in such a way that this makes sense. I think it's pretty clear to the user that they should refresh if they want more data. And given that we have a run ongoing indicator, it should clear up most of the uncertainty. Plus, imagine you are doing a time dependent merge, and then it refreshes on you - it would be super annoying! (This last part could be addressed by a switch to turn it on and off, but I don't see a strong motivation for it anyway).

@jdmulligan - What do you think? Can you think of a good motivation for it? If not, I'll close this.

**Comment by jdmulligan** [comment]
I agree!

**Comment by raymondEhlers** [comment]
Great - closing this!
